### ISSUE TITLE
Brightness setting

### ISSUE THREAD

**Issue by williambout** [SeanCline/Gif2UnicornHat#1]
It would be great to be able to setup the brightness when launching Gif2UnicornHat.
Like `./Gif2UnicornHat loop.gif 0.5`

**Comment by SeanCline** [comment]
Yep, that's been on my todo list. Your request may motivate me to do it. :P

**Comment by SeanCline** [comment]
Alright, I threw something together. Give it a try and let me know if you have any problems.

**Comment by williambout** [comment]
Works perfectly. Thank you.
It would also be great if no parameters detected, to check a config file where you can set the brightness based on the hour of the day.
I don't have knowledge in C++, so I can't really help :/

**Comment by SeanCline** [comment]
I'd considered something to dim the display based on time, or maybe an ambient light sensor, since I have it running 24/7 in an office building.

I ended up rejecting that idea because it adds more complexity to the project than I was really willing to deal with.
